version: "3"
services:
    imaginary:
        image: h2non/imaginary:latest
        volumes:
          - ./media:/mnt/data
        environment:
           PORT: 9000
        command: -enable-url-source -mount /mnt/data
        ports:
          - "9000:9000"
    nginx:
        build: .
        ports:
          - 80:80
        volumes:
          - ./media:/app/media
